### PR TITLE
Merge tag 'LA.UM.7.2.r2-09300-8x98.0'

### PR DESCRIPTION
**Pull request by Flamefire**
Merge tag 'LA.UM.7.2.r2-09300-8x98.0' of https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0

via 

- `git subtree pull --prefix drivers/staging/qcacld-3.0/ https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0 LA.UM.7.2.r2-09300-8x98.0`
- `git subtree pull --prefix drivers/staging/qca-wifi-host-cmn https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn LA.UM.7.2.r2-09300-8x98.0`
- `git subtree pull --prefix drivers/staging/fw-api/ https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/fw-api LA.UM.7.2.r2-09300-8x98.0`

https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn

CC @bananafunction for review

### CODE REVIEW

**Comment by bananafunction** [comment]
> Merge tag 'LA.UM.7.2.r2-09300-8x98.0' of https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0
> 
> via
> 
>     * `git subtree pull --prefix drivers/staging/qcacld-3.0/ https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0 LA.UM.7.2.r2-09300-8x98.0`
> 
>     * `git subtree pull --prefix drivers/staging/qca-wifi-host-cmn https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn LA.UM.7.2.r2-09300-8x98.0`
> 
>     * `git subtree pull --prefix drivers/staging/fw-api/ https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/fw-api LA.UM.7.2.r2-09300-8x98.0`
> 
> 
> https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn
> 
> CC @bananafunction for review

Hi @Flamefire

thank you for merging a lot of stuff into this kernel!
For me, it looks good. I am gonna build the kernel with this PR and flash it to test.
Do you already run this kernel with all the PRs included?

Cheers

**Comment by Flamefire** [comment]
>  Do you already run this kernel with all the PRs included?

Flashed yesterday, no issues so far.

**Comment by derfelot** [comment]
Thanks again. Got some updates for device-side coming up as well

**Comment by Flamefire** [comment]
Great. Please ping me in those PR(s) as I'm building of my forks ATM

**Comment by Flamefire** [comment]
@derfelot Could you remind me of those device-side updates again please? I forgot about them and wanted to make sure I got them :)

**Pull request merged**
