### PR TITLE
Lineage la.um.9.2.r1 merge

### PR DESCRIPTION
**Pull request by Flamefire**
@derfelot This is what we get from a full merge of the LA.UM.9.2.r1-03400-SDMxx0.0 as discussed at https://github.com/whatawurst/android_kernel_sony_msm8998/pull/33#issuecomment-884556783

Marking as a draft as I have yet to check the commits made.

### CODE REVIEW

**Comment by Flamefire** [comment]
Checked the commits/changes: Only thing I'm not quite sure about is 5e09017f84cf393dcc316d2955010a2f21beedb1, the rest looks good and some as actually beneficial changes.

**Comment by derfelot** [comment]
Yeah, besides that everything looks pretty straightforward. 

Just give it a test for a few days and see what happens. If it causes issues you can just revert it again. Let me know how it goes.

**Comment by Flamefire** [comment]
On second thought: It basically renames an IRQ. The new one seems to be used in kernel/sony/msm8998/drivers/leds/leds-qpnp-haptics.c while the old one is/was used in kernel/sony/msm8998/drivers/soc/qcom/qpnp-haptic.c
Do you happen to know anything about that stuff? I'll do some research and see what I can find, then likely try it over the weekend or so

**Comment by derfelot** [comment]
We don't use either of those two drivers from what i remember. You can check the makefiles/kconfigs for those two and see if they are even enabled in our defconfigs. It's been a while since I did the kernel merge, but i am pretty sure that we are using a different (Sony-specific) driver for the vibrator.

**Comment by derfelot** [comment]
Found it, this is ours: https://github.com/whatawurst/android_kernel_sony_msm8998/commit/d44ce15fc3f9f39a4d2a1b51780e8d2aba595733

**Comment by Flamefire** [comment]
Updated to 03500 tag

**Comment by derfelot** [comment]
Thanks, all good here and for Linux PR?

**Comment by Flamefire** [comment]
Running all 3 PRs combined and booted via fastboot for a couple hours now and flashed it now as a ROM which booted successfully.
No issues so far, so good to go from my side.

**Pull request merged**
