### PR TITLE
[lineage-18.1] July Update

### PR DESCRIPTION
**Pull request by Flamefire**
Includes #30

Merged Kernel 4.4.275 from git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux

This corresponds to >= ASB-2021-07-05_4.4-p according to https://android.googlesource.com/kernel/common/+log/refs/heads/android-4.4-p

### CODE REVIEW

**Comment by derfelot** [comment]
I didn't see this PR until now. I included the recent kernel changes in https://github.com/whatawurst/android_kernel_sony_msm8998/pull/30 already. Also, it looks like the commits from https://github.com/whatawurst/android_kernel_sony_msm8998/pull/30 are now squashed into a merge commit of yours, from what I can tell. Please try my updated PR and see if that works, I will try to test it today but I'm not sure I will have time for it, since there are some other changes in yoshino I want to take care of as well.

**Comment by derfelot** [comment]
(closing this for now)

**Comment by derfelot** [comment]
(closing this for now)

**Comment by Flamefire** [comment]
> Also, it looks like the commits from #30 are now squashed into a merge commit of yours

Yeah, took your PR and merged into my branch since #30 was open for so long. Since then included the recent kernel and wanted to provide that here in case you don't have time to do it yourself.

Running this PR (so basically the same as #30) on my phone for 2 days now, no issues so far

**Comment by derfelot** [comment]
Thanks, in that case I'll merge my open one.

Recently it's hard to predict for me when I have the time to wok on Android related things, that's why it was open for so long :) Should have more time again from now on I think.

**Comment by Flamefire** [comment]
Great, thanks and welcome back.
You might want to pick this one too: https://github.com/LineageOS/android_kernel_razer_msm8998/commit/d46db1f472cf55742a7a2db10218cdcc084e0daf

BTW: I was about to start a list of dependent repos, i.e. things like WireGuard or LA.UM which need to be kept up to date in the kernel in addition to the upstream linux kernel. I'd guess you already have some kind of checklist of such things, at least mentally. Would be great if you could write this down for the case when you can't do the updates yourself :)

**Pull request closed without merging**
