### PR TITLE
CIP -st41 & ASB 2023-06 patches

### PR DESCRIPTION
**Pull request by Flamefire**
I merged the latest CIP tag and picked the 2 relevant Qualcomm commits for the 2023-06 ASB from CLO.

The `ASoC` one had a conflict which pointed me at the 3 `asoc` commits which look reasonably enough to include them

### CODE REVIEW

**Comment by derfelot** [comment]
Great, thanks. Was going to do this on the weekend but didn't have the time.

Could you please also add your fix for the microphone issues after the recent patchsets? I assume it's this one? https://github.com/Flamefire/android_kernel_sony_msm8998/commit/6b548b44b51542ee3159a4932ac073dc6c46dbdd

**Comment by derfelot** [comment]
Actually, maybe it was something else as well. IIRC, the problem was the mic volumes were too low for other party to hear you during calls.

**Comment by Flamefire** [comment]
There might be 2 issues: The one fixed by the referenced commit reverting 787686e7dcccc694ee4ab30633d08304f5daf4b1 fixes the issue that when using the headset in a call the microphone can be heard in the earplugs in full volume making it impossible to understand the other party (Reproducer: Start a call with headset plugged in and slightly blow over the microphone -> Loud sound in the earplugs without the revert)

The mic volume being to low might be related and even caused by this but couldn't really reproduce. Might be fixable by changing the xml configuration file, but without being able to reproduce this I can't test it properly, so can't do anything about that right now.

**Comment by derfelot** [comment]
Oh right, I thought it was caused by one of those three ALSA commit from previous CIP tag and related to some Sony modifications.

**Comment by Flamefire** [comment]
Updated

**Pull request merged**
