### PR TITLE
Fix Maps crash issue on Maple

### PR DESCRIPTION
**Pull request by ShujathMohd**

### CODE REVIEW

**Comment by linckandrea** [comment]
Hi shujath i have some questions.

the commit 19eb56782c399f8468a2c96b611b9e60940d96db 
require additional [changes](https://github.com/ZfSODP/kernel_sony_msm-4.9_kernel/commit/8a8baf2946e7bca3aea1a689a28ba9da2950e9df#diff-2e9b86e79e12200e7f98300a379286b3
) 
but at that point we aren't match anything...

in the commit f3d65536b6eb1ad9d2f554d4ac0fd308d66baf99 why did you removed the 4k profile only in ID6 and not in all panels like @Myself5 did [here](https://github.com/CarbonROM/android_kernel_sony_msm8998/commit/1b9d18e42ba753fadded4b3731af5427789e918c)  ?

**Comment by Myself5** [comment]
19eb567 is completely unrelated to any of this.

Given @MFShujath and the other developers involved in the Yoshino-StockDevelopment org closely follow everything I do on maple and havn't been the most careful when it comes to commit authorship in the past, this looks very suspiciously copied the same way it has happened before.

The reason it works for him (assuming it's been tested) is that he probably has an ID6 panel without knowing or caring about the other panels.

In the unlikely event this has been their own discovery the reasoning can be reduced to "They forgot that maple has been shipped with different panels and only adjusted the ID6 one"

**Comment by derfelot** [comment]
yeah I was wondering about that GPU commit, I couldn't find the reference in mdss for the timeout when the low power state there is triggered. can you point me to it? looks kind of ricey to me.

**Comment by linckandrea** [comment]
ulps need to be enabled in panel dts files ([look here](https://github.com/linckandrea/Pop-kernel-poplar-Q/commit/3a82531854b368cb6fba73e00ba66de1824b9719#diff-d28b9d608d0aaef8531401df64e6de33)

note: i'm not sure that the deleting "qcom,mdss-dsi-lp11-init" is needed

edit:
this is [documentation](https://android.googlesource.com/kernel/msm/+/android-msm-bullhead-3.10-marshmallow-dr/Documentation/devicetree/bindings/fb/mdss-dsi-panel.txt) that explain what flags do

**Comment by derfelot** [comment]
I was referring to "This matches the ULPS timeout used in MDSS". Does it? Can you show me where this is set? I can't find it.

nevermind, didn't see your comment in 2nd post for some reason.

**Comment by ShujathMohd** [comment]
> [19eb567](https://github.com/whatawurst/android_kernel_sony_msm8998/commit/19eb56782c399f8468a2c96b611b9e60940d96db) is completely unrelated to any of this.
> 
> Given @MFShujath and the other developers involved in the Yoshino-StockDevelopment org closely follow everything I do on maple and havn't been the most careful when it comes to commit authorship in the past, this looks very suspiciously copied the same way it has happened before.
> 
> The reason it works for him (assuming it's been tested) is that he probably has an ID6 panel without knowing or caring about the other panels.
> 
> In the unlikely event this has been their own discovery the reasoning can be reduced to "They forgot that maple has been shipped with different panels and only adjusted the ID6 one"

Well, I really appreciate the work you have done for Maple , It wouldnt have been possible without you ;) and ofcourse the real masters of yoshino @derfelot  and @cryptomilk 

I have been evolved from a noob and didnt had any knowledge of git when I started, hence missed authorship(will be corrected soon).

Regarding the authorship of removing the 4K timings, It was fixed long way back in April by one of the dev rcmiku (https://forum.xda-developers.com/showpost.php?p=82393785&postcount=6) 
He shared that fix with me(According to him the issue is only on panel 6), He is not on Github so I couldnt give him the authorship.

I can confirm no one reported that issue again after removing the timings from a single panel.

**Comment by Myself5** [comment]
> Regarding the authorship of removing the 4K timings, It was fixed long way back in April by one of the dev rcmiku (forum.xda-developers.com/showpost.php?p=82393785&postcount=6)

Should at least mention him in the commit message then but glad to see it wasn't just copied from somewhere without caring again.

> According to him the issue is only on panel 6

Doubt that given it's not an issue limited to maple but also happens on other devices with multiple resolutions. The panel 6 one might be the only that has horrible crashes and artifacts but the different resolution themselves still have issues (and so they do on e.g. the OnePlus 7T Pro and 8 Pro) where the app only occupies the top left corner of the screen and other issues.

> I can confirm no one reported that issue again after removing the timings from a single panel.

I believe ID6 was the most widespread panel and the other ones were mostly found as chinese replacement panels and similiar, so I wouldn't be surprised if you just didn't come across someone with that panel yet.

**Comment by derfelot** [comment]
should be fixed with https://github.com/whatawurst/android_kernel_sony_msm8998/commit/3df5464bee708e5c347b1348a13b054f8f612e47

**Pull request closed without merging**
