### PR TITLE
November Update

### PR DESCRIPTION
**Pull request by derfelot**
* Merged Linux 4.4.241 kernel
* More changes from Google (CAF Nov. ASB branch)
* Merged Linux 4.4.242 kernel
* Merged Linux 4.4.243 kernel
* Updated WireGuard to v1.0.20201112
* Merged Linux 4.4.244 kernel
* Merged Linux 4.4.245 kernel

### CODE REVIEW

**Comment by derfelot** [comment]
Good to go, but let's see if there are any more updates until November ASB gets merged in LOS.

**Comment by derfelot** [comment]
Hold on in any case. need to push couple more things.

**Comment by bananafunction** [comment]
Hey,
maybe one more to pick:
ANDROID: Temporarily disable XFRM_USER_COMPAT filtering (https://android.googlesource.com/kernel/common/+/1c23a26139e11ca31b16f6e15d41282e9421d717)

**Comment by derfelot** [comment]
Hm, yes. It's also there in the 4.14 update for Samsung. Weird that CAF didn't pick this one.

Ah, it's not part of the ASB, that's why

**Comment by cryptomilk** [comment]
Ready?

**Comment by derfelot** [comment]
Building as we speak. But was fine up to .244, can't see any issues with .245

**Comment by derfelot** [comment]
Builds, boots, works

**Pull request merged**
