### PR TITLE
Lineage 17.1 update

### PR DESCRIPTION
**Pull request by linckandrea**

### CODE REVIEW

**Comment by cryptomilk** [comment]
Where are those `memcmp` patches coming from?

**Comment by linckandrea** [comment]
@4bcaf19  [-->](https://github.com/LineageOS/android_kernel_xiaomi_sm6125/commit/04ee1dbf4dda84b12b4b416b930ec23da10adcdf)

@886cbdc [-->]( https://github.com/LineageOS/android_kernel_xiaomi_sm6125/commit/e6a8117eef314b196b45e4a6c23e9b63cbeb27c2)

**Comment by derfelot** [comment]
Was also having my doubts about the memcmp patch. But seeing as it's applied in bionic libc (just checked) should be fine?

**Comment by cryptomilk** [comment]
The thing is that they might cause issues when updating the kernel. But we could revert them in case this happens.

**Comment by derfelot** [comment]
yes, let's do that. merging this

**Pull request merged**
