### PR TITLE
[WIP] [lineage-19.0] BPF backport

### PR DESCRIPTION
**Pull request by derfelot**
this should be a working backport. bpf is required on A12.

Do not merge yet.

### CODE REVIEW

**Comment by Lollobasic** [comment]
when will the rom be released?

**Comment by shank03** [comment]
> when will the rom be released?

No one knows

**Comment by derfelot** [comment]
> > when will the rom be released?
> 
> No one knows

:)

soon(-ish). It's being tested right now, a couple of things i want to still work out first.

**Comment by derfelot** [comment]
closing this, new one coming.

**Pull request closed without merging**
